### ISSUE TITLE
French accents

### ISSUE THREAD

**Issue by khariche** [vincemann/subtitle-buddy#5]
Hi, french subtitles don't appear correctly. How can I fix this? Is there a way to specifiy a compatible encoding in the application.properties file?
Thanks in advance.
Cheers

**Comment by vincemann** [comment]
Sry for the late reply.
You can convert the file to utf-8 https://subtitletools.com/convert-text-files-to-utf8-online -  worked for me, but I'll still add an encoding key in application.properties and also make sure utf-8 is used by default. Currently it uses your local default encoding. You will also be able to specify 'encoding = ISO-8859-1'  in application.properties, but converting to utf-8 is the best way

**Comment by khariche** [comment]
Thank you very much.
Cheers
